CREATE TABLE USERS (
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO USERS(USERNAME, PASSWORD)
VALUES ('root', '204036a1ef6e7360e536300ea78c6aeb4a9333dd'); /*** student ***/

CREATE TABLE LABORATORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    MINIMAL_POINT DECIMAL NOT NULL,
    PER_QUALITY_MIN FLOAT NOT NULL,
    TUNED_IN_WORKS INT NOT NULL,
    DIFFICULTY VARCHAR(255) NOT NULL,
    /*** link to table the 'USERS' ***/
    THIS_USER VARCHAR(255) NOT NULL,
    FOREIGN KEY (THIS_USER) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE COORDINATES (
    X BIGINT NOT NULL,
    Y INT NOT NULL,
    /*** link to table the 'LABORATORY' ***/
    LAB_ID INT NOT NULL,
    FOREIGN KEY (LAB_ID) REFERENCES LABORATORY(ID) ON DELETE CASCADE
);


CREATE TABLE DISCIPLINE (
    DIS_NAME VARCHAR(255) NOT NULL,
    SELF_STUDY_HOURS INT NOT NULL,
    LABS_COUNT BIGINT NULL,
    /*** link to table the 'LABORATORY' ***/
    LAB_ID INT NOT NULL,
    FOREIGN KEY (LAB_ID) REFERENCES LABORATORY(ID) ON DELETE CASCADE
);