package ru.ifmo.cs.pb.lab8.database.sql.pattern;

public abstract class GET {

      public static final String COLLECTION = "SELECT ID, NAME, CREATION_DATE, MINIMAL_POINT, PER_QUALITY_MIN, TUNED_IN_WORKS, DIFFICULTY, THIS_USER, X, Y, DIS_NAME, SELF_STUDY_HOURS, LABS_COUNT FROM LABORATORY INNER JOIN COORDINATES ON LABORATORY.ID = COORDINATES.LAB_ID INNER JOIN DISCIPLINE ON LABORATORY.ID = DISCIPLINE.LAB_ID";

      public static final String PASSWORD_BY_USER = "SELECT PASSWORD FROM USERS WHERE USERNAME=?";

      public static final String ITEM_BY_ID = "SELECT THIS_USER FROM LABORATORY WHERE ID=?";
}
